version: "3"
services:
  pyborgd:
    build: .
    image: "jrabbit/pyborg:2.0"
    command: poetry run pyborg http --host 0.0.0.0
    volumes:
      - ./docker-brains:/root/.config/pyborg/brains/
    ports:
      - "6661:2001"
  irc:
    build: .
    image: "jrabbit/pyborg:2.0"
    command: poetry run pyborg irc
    depends_on:
      - pyborgd
  discord:
    build: .
    image: "jrabbit/pyborg:2.0"
    environment:
      - PYBORG_HOST=pyborgd
    # env_file: .env
    volumes:
      - ./pyborg/example.discord.toml:/etc/pyborg/discord.toml
    #   - .:/usr/src/pyborg
    command: poetry run pyborg discord --conf-file /etc/pyborg/discord.toml